[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc_version = "0.8.28"

[profile.reserve-index-dtf]
src = "node_modules/@reserve-protocol/reserve-index-dtf/contracts"
out = "node_modules/@reserve-protocol/reserve-index-dtf/out"
cache_path = "cache/dtf-artifacts"
libs = ["node_modules"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
auto_detect_remappings = false
remappings = [
  "forge-std/=node_modules/forge-std/src/",
  "@openzeppelin/contracts/=node_modules/@reserve-protocol/reserve-index-dtf/node_modules/@openzeppelin/contracts/",
  "@openzeppelin/contracts-upgradeable/=node_modules/@reserve-protocol/reserve-index-dtf/node_modules/@openzeppelin/contracts-upgradeable/",
  "@prb/math/=node_modules/@prb/math/",
  "@reserve-protocol/trusted-fillers/=node_modules/@reserve-protocol/trusted-fillers/",
  "@reserve-protocol/reserve-governor/=node_modules/@reserve-protocol/reserve-governor/",
  "@src/=node_modules/@reserve-protocol/reserve-index-dtf/contracts/",
  "@utils/=node_modules/@reserve-protocol/reserve-index-dtf/contracts/utils/",
  "@interfaces/=node_modules/@reserve-protocol/reserve-index-dtf/contracts/interfaces/",
  "@folio/=node_modules/@reserve-protocol/reserve-index-dtf/contracts/folio/",
  "@gov/=node_modules/@reserve-protocol/reserve-index-dtf/contracts/governance/",
  "@deployer/=node_modules/@reserve-protocol/reserve-index-dtf/contracts/deployer/",
  "@periphery/=node_modules/@reserve-protocol/reserve-index-dtf/contracts/periphery/"
]
